apiVersion: apps/v1
kind: Deployment
metadata:
  # 部署名字
  name: test-k8s
spec:
  # 声明副本数目
  replicas: 5
  # 用来查找关联的 Pod，所有标签都匹配才行
  # 关联pod，通过标签 # 选择器
  selector:
    matchLabels:
      app: test-k8s
  # 定义 Pod 相关数据
  template:
    metadata:
      labels:
        app: test-k8s
    spec:
      # 定义容器，可以多个
      containers:
        # 容器名字
        - name: test-k8s
          # 镜像路径
          image: ccr.ccs.tencentyun.com/hannokishi/k8s-test:v3
